Add Bahasa Melayu (ms) support
ChatGPTNextWeb/ChatGPT-Next-Web pull request #3333
Opened 2023-11-20 15:13 UTC by saga0324

2023-11-20 15:28 UTC, H0llyW00dzZ reviewed
need change `new` to `my`

2023-11-20 15:28 UTC, H0llyW00dzZ commented on app/locales/index.ts
> +import new from "./new.ts";
change this to  `my`

2023-11-20 15:28 UTC, H0llyW00dzZ commented on app/locales/index.ts
> +  new
this as well changed to `my`

2023-11-20 15:28 UTC, H0llyW00dzZ commented on app/locales/index.ts
> +  new: "new lang",
this as well changed to `my`

2023-11-20 15:28 UTC, H0llyW00dzZ commented on app/locales/new.ts
> +  export default new;
this as well changed to `my`

2023-11-20 15:34 UTC, H0llyW00dzZ commented
> > need change `new` to `my`
> 
> Thanks a lot. But I think the ISO 639-1 code of Bahasa Melayu is MS, not MY

it's fine because `my` used to be code name of country
`my` = malaysia

2023-11-20 15:39 UTC, H0llyW00dzZ commented
nvm yeah you can changed to ms instead of my

2023-11-21 07:02 UTC, saga0324 reviewed
Fix MY to MS

2023-11-21 07:03 UTC, H0llyW00dzZ reviewed
great

2023-11-21 07:04 UTC, H0llyW00dzZ requested changes
this should be `ms` not a `new`

2023-11-21 07:07 UTC, saga0324 reviewed
Fixed

2023-11-21 07:08 UTC, H0llyW00dzZ approved these changes
nice

2023-12-26 17:25 UTC, closed without merging