Add feature: Support for multiple models on Azure and Azure model mapper
ChatGPTNextWeb/ChatGPT-Next-Web pull request #3344
Opened 2023-11-22 02:24 UTC by shendongming

# Added support for multiple models on Azure; in practice, we will deploy several models on Azure, such as gpt-4, gpt-3.5, etc.

## Two changes:
1. Added a new configuration item: AZURE_OPENAI_MODEL_MAPPER
2. Extended the configuration item: AZURE_URL

## The changes are as follows:

### `AZURE_URL` (optional)

> Example: https://{azure-resource-url}/openai/deployments/{deploy-name} 
> 
> Example: https://xxx.openai.azure.com/openai/deployments/{deploy-name}

Azure deploy url.

If `{deploy-name}` is using the template mode, then it will automatically replace the path based on the model selected by the client. 
If your model name is different from the deployment name, then you need to set the `AZURE_OPENAI_MODEL_MAPPER` parameter.

### `AZURE_OPENAI_MODEL_MAPPER` (optional)
> Default: Empty
> Example: `gpt-3.5-turbo=gpt-35-turbo` means map `gpt-3.5-turbo` to `gpt-35-turbo`

If you are deploying ChatGPT using Azure OpenAI, it is recommended to set the `AZURE_OPENAI_MODEL_MAPPER`. 
The session summarization feature relies on the `gpt-3.5-turbo` model, unless the name of your Azure deployment is the same as it.

2023-11-27 02:24 UTC, H0llyW00dzZ requested changes
this `default: "2023-04",` must made sperate for azure as example, because it will affected for openai and become bad hallucination.

2023-11-27 02:24 UTC, H0llyW00dzZ commented on app/constant.ts
> +  default: "2023-04",
this `default: "2023-04",` must made sperate for azure as example, because it will affected for openai and become bad hallucination.

2023-11-27 02:32 UTC, H0llyW00dzZ commented
> [!WARNING]  
> The `KnowledgeCutOffDate` is intended for system prompts. Exercise caution when changing it, as it must be correctly aligned with the models.

2023-12-01 06:39 UTC, shendongming commented
Thank you
I have set KnowledgeCutOffDate to 2021-09
@H0llyW00dzZ

2024-07-02 16:54 UTC, lloydzhou commented on README_CN.md
> +> Example: `gpt-3.5-turbo=gpt-35-turbo` 意思是 `gpt-3.5-turbo` 映射到 `gpt-35-turbo`
看起来似乎是一个容易在配置文件中实现的方案 @Dogtiti

2024-07-03 06:41 UTC, lloydzhou commented on README_CN.md
> +会话摘要功能依赖gpt-3.5-turbo 这个model,除非你的azure deployment的名字和它相同
可以直接使用CUSTOM_MODELS中配置gpt-4-1106-preview=gpt-4-turbo的方式，等于后面既作为展示名称，也作为deploy_name使用

2024-07-06 02:50 UTC, closed without merging

2024-07-08 03:38 UTC, itcodes commented on README_CN.md
> +会话摘要功能依赖gpt-3.5-turbo 这个model,除非你的azure deployment的名字和它相同
你好，这个最新 readme 文档有了吗？使用 azure 部署的遇到一些麻烦。