feat: Add vision support
ChatGPTNextWeb/ChatGPT-Next-Web pull request #4076
Opened 2024-02-19 20:52 UTC by TheRamU

- Gemini Pro Vision supported
- GPT-4 Vision supported
- Fixed not reporting to the user when Gemini request error
- Image features are now globally supported in this application

![](https://raw.githubusercontent.com/TheRamU/Image/master/image/next-chat-vision-demo.png)

![](https://raw.githubusercontent.com/TheRamU/Image/master/image/next-chat-vision-mobile-demo.png)

2024-02-19 22:10 UTC, H0llyW00dzZ commented
LGTM

2024-02-19 22:44 UTC, H0llyW00dzZ requested changes
Request Change `Summarize` for `gemini-pro` and `gemini-pro-vision`

2024-02-19 22:44 UTC, H0llyW00dzZ commented on app/store/chat.ts
> +  if (currentModel.startsWith("gemini-pro")) {
> [!TIP]
> It's more effective to use `Summarize` with Gemini's own models. For example, `gemini-pro` refers to the Gemini Pro model, and `gemini-pro-vision` refers to the Gemini Pro Vision model. These models are more affordable compared to `OpenAI` hahaha and more efficient, as each model has its own specific token limit. For instance, the token input limit for the `gemini-pro-vision` model is around `12288 tokens`.

Proof:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/ad735b1b-f630-43fd-a3ad-49d6067a58bc)

2024-02-20 00:47 UTC, H0llyW00dzZ commented
Show off

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/50c7be7f-9854-4212-899a-34e016af29f1)

2024-02-20 10:04 UTC, merged

2024-02-21 16:43 UTC, H0llyW00dzZ commented on app/store/chat.ts
> +  if (currentModel.startsWith("gemini-pro")) {
> Gemini Pro Vision does not enable multiturn chat, which limits its role as a "Summarize Model"

rip, its better model, unlike openai `gpt-4-vision-preview`

2024-02-27 02:56 UTC, fengzai6 commented
能否在选中谷歌视觉模型的时候，对话不使用多轮聊天，仅上传单论对话，不用每次使用需要清除上下文

2024-02-27 02:57 UTC, fengzai6 commented
能否在选中谷歌视觉模型的时候，对话不使用多轮聊天，仅上传单次对话，不用每次使用需要清除上下文

2024-03-06 04:34 UTC, PengLingJun commented
Why are my responses using the vision-preview api incomplete

<img width="1586" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/113503995/1e053263-05b2-4199-8a0a-c709c700c49c">

<img width="1617" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/113503995/2b64391b-877a-4f40-a2ee-866c7b80c5fc">