support gpt-4o
ChatGPTNextWeb/ChatGPT-Next-Web pull request #4674
Opened 2024-05-13 21:29 UTC by leo4life2

2024-05-13 21:49 UTC, rhlkmth commented
thank you for this, i updated this in my private fork. Its a pleasure to use.

2024-05-14 03:22 UTC, jinjianming commented
Now there's a problem with the compilation
=># info There appearances to be troublesome with your network connection Retrying
=># info There appearances to be troublesome with your network connection Retrying

2024-05-14 06:24 UTC, fred-bf commented on app/utils.ts
> -  return visionKeywords.some((keyword) => model.includes(keyword)) || isGpt4Turbo;
gpt-4-turbo still do not support vision mode

2024-05-14 06:27 UTC, fred-bf requested changes

2024-05-14 06:27 UTC, fred-bf commented on app/utils.ts
> -  const isGpt4Turbo = model.includes("gpt-4-turbo") && !model.includes("preview");
gpt-4-turbo-preview still do not support vision mode

2024-05-14 06:36 UTC, merged

2024-05-14 15:47 UTC, 04041b commented
> Now there's a problem with the compilation =># info There appearances to be troublesome with your network connection Retrying =># info There appearances to be troublesome with your network connection Retrying

delete yarn.lock, there's problem with npm mirror

2024-05-15 02:13 UTC, leochen12-rgb commented
问一下，基于api部署的gpt-4o官方是否收费