add fanyi add top tip
ChatGPTNextWeb/ChatGPT-Next-Web pull request #5470
Opened 2024-09-19 09:00 UTC by mayfwl

#### 💻 变更类型 | Change Type

- [ ] feat    
- [ ] fix    
- [ ] refactor    
- [ ] perf    
- [ ] style    
- [ ] test    
- [ ] docs    
- [ ] ci    
- [ ] chore    
- [ ] build    

#### 🔀 变更说明 | Description of Change

#### 📝 补充信息 | Additional Information

2024-09-19 09:06 UTC, Dogtiti requested changes

2024-09-19 09:06 UTC, Dogtiti commented on app/components/auth.tsx
> +    const bannerDismissed = localStorage.getItem("bannerDismissed");
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/utils.ts#L321

2024-09-19 09:07 UTC, Dogtiti requested changes

2024-09-19 09:07 UTC, Dogtiti commented on app/icons/www-delete.svg
rename？

2024-09-19 11:12 UTC, Dogtiti requested changes

2024-09-19 11:12 UTC, Dogtiti commented on app/components/auth.tsx
> +  const storage = safeLocalStorage();
放外面

2024-09-19 11:12 UTC, Dogtiti commented on app/components/auth.tsx
> +  }, [storage]);
不需要作为组件内部的依赖性初始化storage

2024-09-24 02:30 UTC, Dogtiti requested changes

2024-09-24 03:24 UTC, mayfwl commented on app/components/auth.tsx
> +  const [isMobile, setIsMobile] = useState(window.innerWidth < 600);
ok

2024-09-24 14:02 UTC, Dogtiti requested changes

2024-09-24 14:02 UTC, Dogtiti commented on app/components/ui-lib.module.scss
> +  max-width: 60%;
不要修改全局样式！

2024-09-24 14:02 UTC, Dogtiti commented on app/components/button.module.scss
> +  // overflow: hidden;
不要修改全局样式！

2024-09-25 02:53 UTC, mayfwl commented on app/components/model-config.tsx
> +          className={styles["select-model"]}
okok

2024-09-25 07:46 UTC, Dogtiti approved these changes

2024-09-25 07:46 UTC, merged